### ISSUE TITLE
Extra characters in the abstract when exported in bibtex and RIS formats

### ISSUE THREAD

**Issue by jmnobrega** [pkp/citationStyleLanguage#95]
When exporting to bibtex or RIS formats the abstract contents include `<p>` and `</p>` (in the form of `&lt;p&gt;` and `&lt;/p&gt;`), at the beginning and end. Those characters are not part of the abstract contents added to the publication.

**Comment by bozana** [comment]
I investigated a little bit and here is what I have found out:

It seems the library we use assumes that the citations are displayed in an HTML page. It returns the citation styles coated withing two <div> elements.
And the library escapes HTML characters, for example in title and abstract. 

Also, our abstract contains HTML elements.

However the BibTex and RIS format are not displayed on the page as the other formats, but provided by us for download. We do remove the <div> elements that we get returned from the library, but our abstract have HTML elements too.

That means that, for example, a title would then look like this there:
`Title &amp; Test`
```
or abstract would look like this:
&amp;lt;p&amp;gt;The antimicrobial, heavy metal resistance patterns and ... (&amp;amp;gt;56.4 kb) encoding .... &amp;lt;/p&amp;gt;
```.

Thus, I can see the following possibilities how to deal with it:

1. Do not provide BibTex and RIS for download, but display them as other styles on the page, so that users can copy & paste them, if needed.
2. Do nothing i.e. leave it as it is. In that case the users will have those HTML tags and escaping when they import the BibTex or RIS format into their citation software.
3. I actually do not think this is a solution, but to mention it here however: to somehow remove HTML elements from our abstract (and title). The HTML escaping will however remain (or we would need to revert it somehow too).

I think I prefer the solution #1.

**Comment by bozana** [comment]
Hmm... Now I see that we save some parts of the title and abstract html encoded, for example:
<p>Abstract: One more test' &lt; <strong>EN &amp; sign </strong> bla bla... </p>
So the only solution is to somehow disable the encoding by the library we use... :-\

**Comment by bozana** [comment]
Hmmm... I think we can use `htmlspecialchars_decode` for download citations BibTeX and RIS

**Comment by jonasraoni** [comment]
Fixes will be covered by https://github.com/pkp/citationStyleLanguage/issues/118
